CREATE TABLE IF NOT EXISTS hyjc_cdm.tdws_yma02n333_comp_cgt_purc_sal_inve_d (
	yma02n333_comp_cgt_purc_sal_inve_tid STRING COMMENT 'TID标识',
	y STRING COMMENT '年',
	q STRING COMMENT '季',
	m STRING COMMENT '月',
	p STRING COMMENT '旬',
	d STRING COMMENT '日',
	d_year STRING COMMENT '年字符',
	d_quarter STRING COMMENT '季度',
	d_month STRING COMMENT '月份',
	d_period STRING COMMENT '旬字符',
	d_day STRING COMMENT '日字符',
	za_div_code STRING COMMENT '行政区划代码',
	za_div_name STRING COMMENT '行政区划',
	ba_org_code STRING COMMENT '烟草行业组织机构代码',
	ba_org_name STRING COMMENT '烟草行业组织机构名称',
	ba_org_shortname STRING COMMENT '组织机构简称',
	ba_org_city_org_code STRING COMMENT '市局组织机构代码',
	ba_org_city_org_name STRING COMMENT '市局组织机构名称',
	ba_org_city_short_name STRING COMMENT '市局组织机构简称',
	za_city_div_code STRING COMMENT '市级行政区划代码',
	za_city_div_name STRING COMMENT '市级行政区划名称',
	ac_cgt_brand_code STRING COMMENT '卷烟品牌代码',
	ac_cgt_brand_name STRING COMMENT '卷烟品牌名称',
	ac_cgt_code STRING COMMENT '卷烟代码',
	ac_cgt_name STRING COMMENT '卷烟名称',
	ac_cgt_pr_type STRING COMMENT '卷烟价类',
	md02_cgt_level STRING COMMENT '卷烟档位',
	ac_cgt_pr_level STRING COMMENT '卷烟档位名称(卷烟属性表价档)',
	ac_cgt_tar_val DECIMAL(54, 18) COMMENT '卷烟焦油量',
	ma02_cgt_ft_flag STRING COMMENT '罚没烟标识',
	ac_cgt_carton_code STRING COMMENT '卷烟代码（条）',
	ac_cgt_carton_packamount DECIMAL(54, 18) COMMENT '卷烟包装支数(条)',
	ac_cgt_prod_type_code STRING COMMENT '卷烟生产类型代码',
	ac_cgt_trade_price DECIMAL(54, 18) COMMENT '卷烟统一批发价',
	ac_cgt_retail_price DECIMAL(54, 18) COMMENT '卷烟指导零售价',
	ac_cgt_tax_allot_price DECIMAL(54, 18) COMMENT '卷烟含税调拨价格',
	ac_cgt_no_tax_allot_price DECIMAL(54, 18) COMMENT '卷烟不含税调拨价',
	ac_cgt_girth DECIMAL(54, 18) COMMENT '卷烟周长',
	ac_cgt_length DECIMAL(54, 18) COMMENT '卷烟烟支长度',
	ac_cgt_totallength DECIMAL(54, 18) COMMENT '卷烟烟支总长度',
	ac_cgt_filterlength DECIMAL(54, 18) COMMENT '卷烟过滤嘴长度',
	mc03_cgt_fact_code STRING COMMENT '卷烟生产点代码',
	ac_cgt_trademark_owner_ba_ins_org_code STRING COMMENT '卷烟商标所有者工业公司代码',
	ac_cgt_trademark_owner_ba_ins_org_name STRING COMMENT '卷烟商标所有者工业公司名称',
	ac_cgt_trademark_owner_ba_ins_org_shortname STRING COMMENT '卷烟商标所有者工业公司简称',
	ac_cgt_trademark_owner STRING COMMENT '卷烟商标所有者',
	ac_cgt_business_way_code STRING COMMENT '卷烟经营方式代码',
	ac_cgt_recorddate STRING COMMENT '卷烟备案日期',
	cig_barstatus STRING COMMENT '条码状态',
	ac_cgt_import_flag_code STRING COMMENT '卷烟进口国产标识代码',
	ad_cigar_type STRING COMMENT '雪茄型号',
	ad_cigar_pr_level_code STRING COMMENT '雪茄烟价格分档代码',
	ad_cigar_mode_code STRING COMMENT '雪茄烟加工方式代码',
	ad_cigar_core_code STRING COMMENT '雪茄烟茄芯分类代码',
	ad_cigar_wrapper_code STRING COMMENT '雪茄烟茄衣分类代码',
	ad_cigar_weight DECIMAL(54, 18) COMMENT '雪茄烟单支重量',
	is_bsnx STRING COMMENT '是否商业内销标识',
	is_innx STRING COMMENT '是否工业内销标识',
	ad_gigar_import_flag STRING COMMENT '是否雪茄烟',
	ac_cgt_tiny_flag STRING COMMENT '卷烟细支烟标识',
	ac_cgt_medium_brance_flag STRING COMMENT '卷烟中支烟标识',
	ac_cgt_sgort_brance_flag STRING COMMENT '卷烟短支烟标识',
	ac_cgt_pearl_flag STRING COMMENT '卷烟爆珠烟标识',
	ac_key_brand_flag STRING COMMENT '重点品牌标识',
	cig_is_low STRING COMMENT '是否低价位',
	is_high_price_brand STRING COMMENT '是否高价位品牌',
	ac_cgt_high_flag STRING COMMENT '卷烟高端标识',
	md02_cgt_10th_com_buy_in_qty DECIMAL(54, 18) COMMENT '卷烟商业购进到货量（万支）',
	md02_cgt_10th_com_buy_in_amt DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额（万元）',
	md02_cgt_10th_com_buy_in_qty_l DECIMAL(54, 18) COMMENT '卷烟商业购进到货量同期（万支）',
	md02_cgt_10th_com_buy_in_amt_l DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额同期（万元）',
	md03_cgt_com_10th_sortout_qty DECIMAL(54, 18) COMMENT '卷烟分拣移出量（万支）',
	md03_cgt_com_10th_sortout_amt DECIMAL(54, 18) COMMENT '卷烟分拣移出金额（万元）',
	md03_cgt_com_10th_sortout_qty_l DECIMAL(54, 18) COMMENT '卷烟分拣移出量同期（万支）',
	md03_cgt_com_10th_sortout_amt_l DECIMAL(54, 18) COMMENT '卷烟分拣移出金额同期（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty DECIMAL(54, 18) COMMENT '卷烟零售户退货量（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt DECIMAL(54, 18) COMMENT '卷烟零售户退货金额（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_l DECIMAL(54, 18) COMMENT '卷烟零售户退货量同期（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_l DECIMAL(54, 18) COMMENT '卷烟零售户退货金额同期（万元）',
	md02_cgt_10th_com_buy_back_out_qty DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量（万支）',
	md02_cgt_10th_com_buy_back_amt DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额（万元）',
	md02_cgt_10th_com_buy_back_out_qty_l DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量同期（万支）',
	md02_cgt_10th_com_buy_back_amt_l DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额同期（万元）',
	md03_cgt_10th_com_sort_qty DECIMAL(54, 18) COMMENT '卷烟商业分拣量（万支）',
	md03_cgt_10th_com_sort_amt DECIMAL(54, 18) COMMENT '卷烟商业分拣金额（万元）',
	md03_cgt_10th_com_sort_qty_l DECIMAL(54, 18) COMMENT '卷烟商业分拣量同期（万支）',
	md03_cgt_10th_com_sort_amt_l DECIMAL(54, 18) COMMENT '卷烟商业分拣金额同期（万元）',
	md03_cgt_10th_com_end_stk_qty DECIMAL(54, 18) COMMENT '卷烟商业期末库存量（万支）',
	md03_cgt_10th_com_end_stk_amt DECIMAL(54, 18) COMMENT '卷烟商业期末库存额（万元）',
	md03_cgt_10th_com_end_stk_qty_l DECIMAL(54, 18) COMMENT '卷烟商业期末库存量同期（万支）',
	md03_cgt_10th_com_end_stk_amt_l DECIMAL(54, 18) COMMENT '卷烟商业期末库存额同期（万元）',
	md04_cgt_10th_com_self_supp_qty DECIMAL(54, 18) COMMENT '卷烟自营店销售量（万支）',
	md04_cgt_10th_com_self_supp_amt DECIMAL(54, 18) COMMENT '卷烟自营店销售金额（万元）',
	md04_cgt_10th_com_self_supp_qty_l DECIMAL(54, 18) COMMENT '卷烟自营店销售量同期（万支）',
	md04_cgt_10th_com_self_supp_amt_l DECIMAL(54, 18) COMMENT '卷烟自营店销售金额同期（万元）',
	md03_cgt_10th_com_buy_qty DECIMAL(54, 18) COMMENT '商业购进量（万支）',
	md03_cgt_10th_com_buy_qty_l DECIMAL(54, 18) COMMENT '商业同期购进量(万支)',
	md03_cgt_10th_com_buy_amt DECIMAL(54, 18) COMMENT '商业购进金额(万元)',
	md03_cgt_ft_10th_com_buy_amt_l DECIMAL(54, 18) COMMENT '商业同期购进金额(万元)',
	md03_cgt_10th_com_sale_qty DECIMAL(54, 18) COMMENT '卷烟销量(万支)',
	md03_cgt_10th_com_sale_qty_l DECIMAL(54, 18) COMMENT '卷烟同期销量(万支)',
	md04_cgt_10th_com_amt DECIMAL(54, 18) COMMENT '卷烟销售金额(万元)',
	md04_cgt_10th_com_amt_l DECIMAL(54, 18) COMMENT '卷烟同期销售金额(万元)',
	md03_cgt_10th_com_sale_qty_m_a DECIMAL(54, 18) COMMENT '卷烟销量月累计(万支)',
	ma02_cgt_10th_com_sale_amt_m_a DECIMAL(54, 18) COMMENT '卷烟销售金额月累计（万元）',
	create_time DATETIME COMMENT '创建时间'
)
PARTITIONED BY (
	ds STRING
)
STORED AS ALIORC
TBLPROPERTIES (
	'comment' = '商业_卷烟购销存日表'
)
LIFECYCLE 7;

CREATE TABLE IF NOT EXISTS hyjc_cdm.tdws_yma02n333_comp_cgt_purc_sal_inve_m (
	yma02n333_comp_cgt_purc_sal_inve_tid STRING COMMENT 'TID标识',
	y STRING COMMENT '年',
	q STRING COMMENT '季',
	m STRING COMMENT '月',
	p STRING COMMENT '旬',
	d STRING COMMENT '日',
	d_year STRING COMMENT '年字符',
	d_quarter STRING COMMENT '季度',
	d_month STRING COMMENT '月字符',
	d_period STRING COMMENT '旬字符',
	d_day STRING COMMENT '日字符',
	za_div_code STRING COMMENT '行政区划代码',
	za_div_name STRING COMMENT '行政区划',
	ba_org_code STRING COMMENT '烟草行业组织机构代码',
	ba_org_name STRING COMMENT '烟草行业组织机构名称',
	ba_org_shortname STRING COMMENT '组织机构简称',
	ba_org_city_org_code STRING COMMENT '市局组织机构代码',
	ba_org_city_org_name STRING COMMENT '市局组织机构名称',
	ba_org_city_short_name STRING COMMENT '市局组织机构简称',
	za_city_div_code STRING COMMENT '市级行政区划代码',
	za_city_div_name STRING COMMENT '市级行政区划名称',
	ac_cgt_brand_code STRING COMMENT '卷烟品牌代码',
	ac_cgt_brand_name STRING COMMENT '卷烟品牌名称',
	ac_cgt_code STRING COMMENT '卷烟代码',
	ac_cgt_name STRING COMMENT '卷烟名称',
	ac_cgt_pr_type STRING COMMENT '卷烟价类',
	md02_cgt_level STRING COMMENT '卷烟档位',
	ac_cgt_pr_level STRING COMMENT '卷烟档位名称(卷烟属性表价档)',
	ac_cgt_tar_val DECIMAL(54, 18) COMMENT '卷烟焦油量',
	ma02_cgt_ft_flag STRING COMMENT '罚没烟标识',
	ac_cgt_carton_code STRING COMMENT '卷烟代码（条）',
	ac_cgt_carton_packamount DECIMAL(54, 18) COMMENT '卷烟包装支数(条)',
	ac_cgt_prod_type_code STRING COMMENT '卷烟生产类型代码',
	ac_cgt_trade_price DECIMAL(54, 18) COMMENT '卷烟统一批发价',
	ac_cgt_retail_price DECIMAL(54, 18) COMMENT '卷烟指导零售价',
	ac_cgt_tax_allot_price DECIMAL(54, 18) COMMENT '卷烟含税调拨价格',
	ac_cgt_no_tax_allot_price DECIMAL(54, 18) COMMENT '卷烟不含税调拨价',
	ac_cgt_girth DECIMAL(54, 18) COMMENT '卷烟周长',
	ac_cgt_length DECIMAL(54, 18) COMMENT '卷烟烟支长度',
	ac_cgt_totallength DECIMAL(54, 18) COMMENT '卷烟烟支总长度',
	ac_cgt_filterlength DECIMAL(54, 18) COMMENT '卷烟过滤嘴长度',
	mc03_cgt_fact_code STRING COMMENT '卷烟生产点代码',
	ac_cgt_trademark_owner_ba_ins_org_code STRING COMMENT '卷烟商标所有者工业公司代码',
	ac_cgt_trademark_owner_ba_ins_org_name STRING COMMENT '卷烟商标所有者工业公司名称',
	ac_cgt_trademark_owner_ba_ins_org_shortname STRING COMMENT '卷烟商标所有者工业公司简称',
	ac_cgt_trademark_owner STRING COMMENT '卷烟商标所有者',
	ac_cgt_business_way_code STRING COMMENT '卷烟经营方式代码',
	ac_cgt_recorddate STRING COMMENT '卷烟备案日期',
	cig_barstatus STRING COMMENT '条码状态',
	ac_cgt_import_flag_code STRING COMMENT '卷烟进口国产标识代码',
	ad_cigar_type STRING COMMENT '雪茄型号',
	ad_cigar_pr_level_code STRING COMMENT '雪茄烟价格分档代码',
	ad_cigar_mode_code STRING COMMENT '雪茄烟加工方式代码',
	ad_cigar_core_code STRING COMMENT '雪茄烟茄芯分类代码',
	ad_cigar_wrapper_code STRING COMMENT '雪茄烟茄衣分类代码',
	ad_cigar_weight DECIMAL(54, 18) COMMENT '雪茄烟单支重量',
	is_bsnx STRING COMMENT '是否商业内销标识',
	is_innx STRING COMMENT '是否工业内销标识',
	ad_gigar_import_flag STRING COMMENT '是否雪茄烟',
	ac_cgt_tiny_flag STRING COMMENT '卷烟细支烟标识',
	ac_cgt_medium_brance_flag STRING COMMENT '卷烟中支烟标识',
	ac_cgt_sgort_brance_flag STRING COMMENT '卷烟短支烟标识',
	ac_cgt_pearl_flag STRING COMMENT '卷烟爆珠烟标识',
	ac_key_brand_flag STRING COMMENT '重点品牌标识',
	cig_is_low STRING COMMENT '是否低价位',
	is_high_price_brand STRING COMMENT '是否高价位品牌',
	ac_cgt_high_flag STRING COMMENT '卷烟高端标识',
	md02_cgt_10th_com_buy_in_qty_y_a DECIMAL(54, 18) COMMENT '卷烟商业购进到货量年累计（万支）',
	md03_cgt_10th_com_buy_in_amt_y_a DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额年累计（万元）',
	md03_cgt_10th_com_buy_in_qty_y_al DECIMAL(54, 18) COMMENT '卷烟商业购进到货量同期年累计(万支)',
	md02_cgt_10th_com_buy_in_amt_y_al DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额同期年累计（万元）',
	md02_cgt_10th_com_buy_in_qty_q_a DECIMAL(54, 18) COMMENT '卷烟商业购进到货量季累计（万支）',
	md02_cgt_10th_com_buy_in_amt_q_a DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额季累计（万元）',
	md02_cgt_10th_com_buy_in_qty_q_al DECIMAL(54, 18) COMMENT '卷烟商业购进到货量同期季累计（万支）',
	md02_cgt_10th_com_buy_in_amt_q_al DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额同期季累计（万元）',
	md02_cgt_10th_com_buy_in_qty_m_a DECIMAL(54, 18) COMMENT '卷烟商业购进到货量月累计（万支）',
	md03_cgt_10th_com_buy_in_amt_m_a DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额月累计（万元）',
	md02_cgt_10th_com_buy_in_qty_m_al DECIMAL(54, 18) COMMENT '卷烟商业购进到货量同期月累计（万支）',
	md02_cgt_10th_com_buy_in_amt_m_al DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额同期月累计（万元）',
	md03_cgt_com_10th_sortout_qty_y_a DECIMAL(54, 18) COMMENT '卷烟分拣移出量年累计（万支）',
	md03_cgt_com_10th_sortout_amt_y_a DECIMAL(54, 18) COMMENT '卷烟分拣移出金额年累计（万元）',
	md03_cgt_com_10th_sortout_qty_y_al DECIMAL(54, 18) COMMENT '卷烟分拣移出量同期年累计（万支）',
	md03_cgt_com_10th_sortout_amt_y_al DECIMAL(54, 18) COMMENT '卷烟分拣移出金额同期年累计（万元）',
	md03_cgt_com_10th_sortout_qty_q_a DECIMAL(54, 18) COMMENT '卷烟分拣移出量季累计（万支）',
	md03_cgt_com_10th_sortout_amt_q_a DECIMAL(54, 18) COMMENT '卷烟分拣移出金额季累计（万元）',
	md03_cgt_com_10th_sortout_qty_q_al DECIMAL(54, 18) COMMENT '卷烟分拣移出量同期季累计（万支）',
	md03_cgt_com_10th_sortout_amt_q_al DECIMAL(54, 18) COMMENT '卷烟分拣移出金额同期季累计（万元）',
	md03_cgt_com_10th_sortout_qty_m_a DECIMAL(54, 18) COMMENT '卷烟分拣移出量月累计（万支）',
	md03_cgt_com_10th_sortout_amt_m_a DECIMAL(54, 18) COMMENT '卷烟分拣移出金额月累计（万元）',
	md03_cgt_com_10th_sortout_qty_m_al DECIMAL(54, 18) COMMENT '卷烟分拣移出量同期月累计（万支）',
	md03_cgt_com_10th_sortout_amt_m_al DECIMAL(54, 18) COMMENT '卷烟分拣移出金额同期月累计（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_y_a DECIMAL(54, 18) COMMENT '卷烟零售户退货量年累计（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_y_a DECIMAL(54, 18) COMMENT '卷烟零售户退货金额年累计（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_y_al DECIMAL(54, 18) COMMENT '卷烟零售户退货量同期年累计（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_y_al DECIMAL(54, 18) COMMENT '卷烟零售户退货金额同期年累计（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_q_a DECIMAL(54, 18) COMMENT '卷烟零售户退货量季累计（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_q_a DECIMAL(54, 18) COMMENT '卷烟零售户退货金额季累计（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_q_al DECIMAL(54, 18) COMMENT '卷烟零售户退货量同期季累计（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_q_al DECIMAL(54, 18) COMMENT '卷烟零售户退货金额同期季累计（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_m_a DECIMAL(54, 18) COMMENT '卷烟零售户退货量月累计（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_m_a DECIMAL(54, 18) COMMENT '卷烟零售户退货金额月累计（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_m_al DECIMAL(54, 18) COMMENT '卷烟零售户退货量同期月累计（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_m_al DECIMAL(54, 18) COMMENT '卷烟零售户退货金额同期月累计（万元）',
	md02_cgt_10th_com_buy_back_out_qty_y_a DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量年累计（万支）',
	md02_cgt_10th_com_buy_back_amt_y_a DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额年累计（万元）',
	md02_cgt_10th_com_buy_back_out_qty_y_al DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量同期年累计（万支）',
	md02_cgt_10th_com_buy_back_amt_y_al DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额同期年累计（万元）',
	md02_cgt_10th_com_buy_back_out_qty_q_a DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量季累计（万支）',
	md02_cgt_10th_com_buy_back_amt_q_a DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额季累计（万元）',
	md02_cgt_10th_com_buy_back_out_qty_q_al DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量同期季累计（万支）',
	md02_cgt_10th_com_buy_back_amt_q_al DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额同期季累计（万元）',
	md02_cgt_10th_com_buy_back_out_qty_m_a DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量月累计（万支）',
	md02_cgt_10th_com_buy_back_amt_m_a DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额月累计（万元）',
	md02_cgt_10th_com_buy_back_out_qty_m_al DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量同期月累计（万支）',
	md02_cgt_10th_com_buy_back_amt_m_al DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额同期月累计（万元）',
	md03_cgt_10th_com_sort_qty_y_a DECIMAL(54, 18) COMMENT '卷烟商业分拣量年累计（万支）',
	md03_cgt_10th_com_sort_amt_y_a DECIMAL(54, 18) COMMENT '卷烟商业分拣金额年累计（万元）',
	md03_cgt_10th_com_sort_qty_y_al DECIMAL(54, 18) COMMENT '卷烟商业分拣量同期年累计（万支）',
	md03_cgt_10th_com_sort_amt_y_al DECIMAL(54, 18) COMMENT '卷烟商业分拣金额同期年累计（万元）',
	md03_cgt_10th_com_sort_qty_q_a DECIMAL(54, 18) COMMENT '卷烟商业分拣量季累计（万支）',
	md03_cgt_10th_com_sort_amt_q_a DECIMAL(54, 18) COMMENT '卷烟商业分拣金额季累计（万元）',
	md03_cgt_10th_com_sort_qty_q_al DECIMAL(54, 18) COMMENT '卷烟商业分拣量同期季累计（万支）',
	md03_cgt_10th_com_sort_amt_q_al DECIMAL(54, 18) COMMENT '卷烟商业分拣金额同期季累计（万元）',
	md03_cgt_10th_com_sort_qty_m_a DECIMAL(54, 18) COMMENT '卷烟商业分拣量月累计（万支）',
	md03_cgt_10th_com_sort_amt_m_a DECIMAL(54, 18) COMMENT '卷烟商业分拣金额月累计（万元）',
	md03_cgt_10th_com_sort_qty_m_al DECIMAL(54, 18) COMMENT '卷烟商业分拣量同期月累计（万支）',
	md03_cgt_10th_com_sort_amt_m_al DECIMAL(54, 18) COMMENT '卷烟商业分拣金额同期月累计（万元）',
	md04_cgt_10th_com_self_supp_qty_y_a DECIMAL(54, 18) COMMENT '卷烟自营店销售量年累计（万支）',
	md04_cgt_10th_com_self_supp_amt_y_a DECIMAL(54, 18) COMMENT '卷烟自营店销售金额年累计（万元）',
	md04_cgt_10th_com_self_supp_qty_y_al DECIMAL(54, 18) COMMENT '卷烟自营店销售量同期年累计（万支）',
	md04_cgt_10th_com_self_supp_amt_y_al DECIMAL(54, 18) COMMENT '卷烟自营店销售金额同期年累计（万元）',
	md04_cgt_10th_com_self_supp_qty_q_a DECIMAL(54, 18) COMMENT '卷烟自营店销售量季累计（万支）',
	md04_cgt_10th_com_self_supp_amt_q_a DECIMAL(54, 18) COMMENT '卷烟自营店销售金额季累计（万元）',
	md04_cgt_10th_com_self_supp_qty_q_al DECIMAL(54, 18) COMMENT '卷烟自营店销售量同期季累计（万支）',
	md04_cgt_10th_com_self_supp_amt_q_al DECIMAL(54, 18) COMMENT '卷烟自营店销售金额同期季累计（万元）',
	md04_cgt_10th_com_self_supp_qty_m_a DECIMAL(54, 18) COMMENT '卷烟自营店销售量月累计（万支）',
	md04_cgt_10th_com_self_supp_amt_m_a DECIMAL(54, 18) COMMENT '卷烟自营店销售金额月累计（万元）',
	md04_cgt_10th_com_self_supp_qty_m_al DECIMAL(54, 18) COMMENT '卷烟自营店销售量同期月累计（万支）',
	md04_cgt_10th_com_self_supp_amt_m_al DECIMAL(54, 18) COMMENT '卷烟自营店销售金额同期月累计（万元）',
	md03_cgt_10th_com_end_stk_qty DECIMAL(54, 18) COMMENT '卷烟商业期末库存量（万支）',
	md03_cgt_10th_com_end_stk_amt DECIMAL(54, 18) COMMENT '卷烟商业期末库存额（万元）',
	md03_cgt_10th_com_end_stk_qty_l DECIMAL(54, 18) COMMENT '卷烟商业期末库存量同期（万支）',
	md03_cgt_10th_com_end_stk_amt_l DECIMAL(54, 18) COMMENT '卷烟商业期末库存额同期（万元）',
	md03_cgt_10th_com_buy_qty_y_a DECIMAL(54, 18) COMMENT '商业购进量年累计(万支)',
	md03_cgt_ft_10th_com_buy_amt_y_a DECIMAL(54, 18) COMMENT '商业购进金额年累计(万元)',
	md03_cgt_10th_com_buy_qty_y_al DECIMAL(54, 18) COMMENT '商业购进量同期年累计(万支)',
	md03_cgt_ft_10th_com_buy_amt_y_al DECIMAL(54, 18) COMMENT '商业购进金额同期年累计(万元)',
	md03_cgt_10th_com_buy_qty_m_a DECIMAL(54, 18) COMMENT '商业购进量月累计（万支）',
	md02_cgt_10th_com_buy_in_amt_m_a DECIMAL(54, 18) COMMENT '商业购进金额月累计(万元)',
	md03_cgt_10th_com_buy_qty_m_al DECIMAL(54, 18) COMMENT '商业购进量同期月累计（万支）',
	md03_cgt_10th_com_buy_in_amt_m_al DECIMAL(54, 18) COMMENT '商业购进金额同期月累计(万元)',
	md03_cgt_10th_com_sale_qty_y_a DECIMAL(54, 18) COMMENT '卷烟销量年累计(万支)',
	md03_cgt_10th_com_sale_amt_y_a DECIMAL(54, 18) COMMENT '卷烟销售金额年累计(万元)',
	ma02_cgt_10th_com_sal_qty_y_a_l DECIMAL(54, 18) COMMENT '卷烟销量同期年累计(万支)',
	md03_cgt_10th_com_sale_amt_y_al DECIMAL(54, 18) COMMENT '卷烟销售金额同期年累计(万元)',
	md03_cgt_10th_com_sale_qty_m_a DECIMAL(54, 18) COMMENT '卷烟销量月累计（万支）',
	ma02_cgt_10th_com_sale_amt_m_a DECIMAL(54, 18) COMMENT '卷烟销售金额月累计（万元）',
	md03_cgt_10th_com_sale_qty_m_al DECIMAL(54, 18) COMMENT '卷烟销量同期月累计（万支）',
	md03_cgt_10th_com_sale_amt_m_al DECIMAL(54, 18) COMMENT '卷烟销售金额同期月累计（万元）',
	create_time DATETIME COMMENT '创建时间'
)
PARTITIONED BY (
	ds STRING
)
STORED AS ALIORC
TBLPROPERTIES (
	'comment' = '商业_卷烟购销存月表'
)
LIFECYCLE 7;




CREATE TABLE IF NOT EXISTS hyjc_cdm.tdws_yma02n333_comp_cgt_purc_sal_inve_y (
	yma02n333_comp_cgt_purc_sal_inve_tid STRING COMMENT 'TID标识',
	y STRING COMMENT '年',
	q STRING COMMENT '季',
	m STRING COMMENT '月',
	p STRING COMMENT '旬',
	d STRING COMMENT '日',
	d_year STRING COMMENT '年字符',
	d_quarter STRING COMMENT '季度季度',
	d_month STRING COMMENT '月份',
	d_period STRING COMMENT '旬字符',
	d_day STRING COMMENT '日字符',
	za_div_code STRING COMMENT '行政区划代码',
	za_div_name STRING COMMENT '行政区划',
	ba_org_code STRING COMMENT '烟草行业组织机构代码',
	ba_org_name STRING COMMENT '烟草行业组织机构名称',
	ba_org_shortname STRING COMMENT '组织机构简称',
	ba_org_city_org_code STRING COMMENT '市局组织机构代码',
	ba_org_city_org_name STRING COMMENT '市局组织机构名称',
	ba_org_city_short_name STRING COMMENT '市局组织机构简称',
	za_city_div_code STRING COMMENT '市级行政区划代码',
	za_city_div_name STRING COMMENT '市级行政区划名称',
	ac_cgt_brand_code STRING COMMENT '卷烟品牌代码',
	ac_cgt_brand_name STRING COMMENT '卷烟品牌名称',
	ac_cgt_code STRING COMMENT '卷烟代码',
	ac_cgt_name STRING COMMENT '卷烟名称',
	ac_cgt_pr_type STRING COMMENT '卷烟价类',
	md02_cgt_level STRING COMMENT '卷烟档位',
	ac_cgt_pr_level STRING COMMENT '卷烟档位(卷烟属性表价档)',
	ac_cgt_tar_val DECIMAL(54, 18) COMMENT '卷烟焦油量',
	ma02_cgt_ft_flag STRING COMMENT '罚没烟标识',
	ac_cgt_carton_code STRING COMMENT '卷烟代码（条）',
	ac_cgt_carton_packamount DECIMAL(54, 18) COMMENT '卷烟包装支数(条)',
	ac_cgt_prod_type_code STRING COMMENT '卷烟生产类型代码',
	ac_cgt_trade_price DECIMAL(54, 18) COMMENT '卷烟统一批发价',
	ac_cgt_retail_price DECIMAL(54, 18) COMMENT '卷烟指导零售价',
	ac_cgt_tax_allot_price DECIMAL(54, 18) COMMENT '卷烟含税调拨价格',
	ac_cgt_no_tax_allot_price DECIMAL(54, 18) COMMENT '卷烟不含税调拨价',
	ac_cgt_girth DECIMAL(54, 18) COMMENT '卷烟周长',
	ac_cgt_length DECIMAL(54, 18) COMMENT '卷烟烟支长度',
	ac_cgt_totallength DECIMAL(54, 18) COMMENT '卷烟烟支总长度',
	ac_cgt_filterlength DECIMAL(54, 18) COMMENT '卷烟过滤嘴长度',
	mc03_cgt_fact_code STRING COMMENT '卷烟生产点代码',
	ac_cgt_trademark_owner_ba_ins_org_code STRING COMMENT '卷烟商标所有者工业公司代码',
	ac_cgt_trademark_owner_ba_ins_org_name STRING COMMENT '卷烟商标所有者工业公司名称',
	ac_cgt_trademark_owner_ba_ins_org_shortname STRING COMMENT '卷烟商标所有者工业公司简称',
	ac_cgt_trademark_owner STRING COMMENT '卷烟商标所有者',
	ac_cgt_business_way_code STRING COMMENT '卷烟经营方式代码',
	ac_cgt_recorddate STRING COMMENT '卷烟备案日期',
	cig_barstatus STRING COMMENT '条码状态',
	ac_cgt_import_flag_code STRING COMMENT '卷烟进口国产标识代码',
	ad_cigar_type STRING COMMENT '雪茄型号',
	ad_cigar_pr_level_code STRING COMMENT '雪茄烟价格分档代码',
	ad_cigar_mode_code STRING COMMENT '雪茄烟加工方式代码',
	ad_cigar_core_code STRING COMMENT '雪茄烟茄芯分类代码',
	ad_cigar_wrapper_code STRING COMMENT '雪茄烟茄衣分类代码',
	ad_cigar_weight DECIMAL(54, 18) COMMENT '雪茄烟单支重量',
	is_bsnx STRING COMMENT '是否商业内销标识',
	is_innx STRING COMMENT '是否工业内销标识',
	ad_gigar_import_flag STRING COMMENT '是否雪茄烟',
	ac_cgt_tiny_flag STRING COMMENT '卷烟细支烟标识',
	ac_cgt_medium_brance_flag STRING COMMENT '卷烟中支烟标识',
	ac_cgt_sgort_brance_flag STRING COMMENT '卷烟短支烟标识',
	ac_cgt_pearl_flag STRING COMMENT '卷烟爆珠烟标识',
	ac_key_brand_flag STRING COMMENT '重点品牌标识',
	cig_is_low STRING COMMENT '是否低价位',
	is_high_price_brand STRING COMMENT '是否高价位品牌',
	ac_cgt_high_flag STRING COMMENT '卷烟高端标识',
	md02_cgt_10th_com_buy_in_qty_y_a DECIMAL(54, 18) COMMENT '卷烟商业购进到货量年累计（万支）',
	md03_cgt_10th_com_buy_in_amt_y_a DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额年累计（万元）',
	md03_cgt_10th_com_buy_in_qty_y_al DECIMAL(54, 18) COMMENT '卷烟商业购进到货量同期年累计(万支)',
	md02_cgt_10th_com_buy_in_amt_y_al DECIMAL(54, 18) COMMENT '卷烟商业购进到货金额同期年累计（万元）',
	md03_cgt_com_10th_sortout_qty_y_a DECIMAL(54, 18) COMMENT '卷烟分拣移出量年累计（万支）',
	md03_cgt_com_10th_sortout_amt_y_a DECIMAL(54, 18) COMMENT '卷烟分拣移出金额年累计（万元）',
	md03_cgt_com_10th_sortout_qty_y_al DECIMAL(54, 18) COMMENT '卷烟分拣移出量同期年累计（万支）',
	md03_cgt_com_10th_sortout_amt_y_al DECIMAL(54, 18) COMMENT '卷烟分拣移出金额同期年累计（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_y_a DECIMAL(54, 18) COMMENT '卷烟零售户退货量年累计（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_y_a DECIMAL(54, 18) COMMENT '卷烟零售户退货金额年累计（万元）',
	md03_cgt_10th_com_rtl_cust_back_qty_y_al DECIMAL(54, 18) COMMENT '卷烟零售户退货量同期年累计（万支）',
	md03_cgt_10th_com_rtl_cust_back_amt_y_al DECIMAL(54, 18) COMMENT '卷烟零售户退货金额同期年累计（万元）',
	md02_cgt_10th_com_buy_back_out_qty_y_a DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量年累计（万支）',
	md02_cgt_10th_com_buy_back_amt_y_a DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额年累计（万元）',
	md02_cgt_10th_com_buy_back_out_qty_y_al DECIMAL(54, 18) COMMENT '卷烟商业购进退货出库量同期年累计（万支）',
	md02_cgt_10th_com_buy_back_amt_y_al DECIMAL(54, 18) COMMENT '卷烟商业购进退货金额同期年累计（万元）',
	md03_cgt_10th_com_sort_qty_y_a DECIMAL(54, 18) COMMENT '卷烟商业分拣量年累计（万支）',
	md03_cgt_10th_com_sort_amt_y_a DECIMAL(54, 18) COMMENT '卷烟商业分拣金额年累计（万元）',
	md03_cgt_10th_com_sort_qty_y_al DECIMAL(54, 18) COMMENT '卷烟商业分拣量同期年累计（万支）',
	md03_cgt_10th_com_sort_amt_y_al DECIMAL(54, 18) COMMENT '卷烟商业分拣金额同期年累计（万元）',
	md04_cgt_10th_com_self_supp_qty_y_a DECIMAL(54, 18) COMMENT '卷烟自营店销售量年累计（万支）',
	md04_cgt_10th_com_self_supp_amt_y_a DECIMAL(54, 18) COMMENT '卷烟自营店销售金额年累计（万元）',
	md04_cgt_10th_com_self_supp_qty_y_al DECIMAL(54, 18) COMMENT '卷烟自营店销售量同期年累计（万支）',
	md04_cgt_10th_com_self_supp_amt_y_al DECIMAL(54, 18) COMMENT '卷烟自营店销售金额同期年累计（万元）',
	md03_cgt_10th_com_end_stk_qty DECIMAL(54, 18) COMMENT '卷烟商业期末库存量（万支）',
	md03_cgt_10th_com_end_stk_amt DECIMAL(54, 18) COMMENT '卷烟商业期末库存额（万元）',
	md03_cgt_10th_com_end_stk_qty_l DECIMAL(54, 18) COMMENT '卷烟商业期末库存量同期（万支）',
	md03_cgt_10th_com_end_stk_amt_l DECIMAL(54, 18) COMMENT '卷烟商业期末库存额同期（万元）',
	md03_cgt_10th_com_buy_qty_y_a DECIMAL(54, 18) COMMENT '商业购进量年累计(万支)',
	md03_cgt_ft_10th_com_buy_amt_y_a DECIMAL(54, 18) COMMENT '商业购进金额年累计(万元)',
	md03_cgt_10th_com_buy_qty_y_al DECIMAL(54, 18) COMMENT '商业购进量同期年累计(万支)',
	md03_cgt_ft_10th_com_buy_amt_y_al DECIMAL(54, 18) COMMENT '商业购进金额同期年累计(万元)',
	md03_cgt_10th_com_sale_qty_y_a DECIMAL(54, 18) COMMENT '卷烟销量年累计(万支)',
	md03_cgt_10th_com_sale_amt_y_a DECIMAL(54, 18) COMMENT '卷烟销售金额年累计(万元)',
	ma02_cgt_10th_com_sal_qty_y_a_l DECIMAL(54, 18) COMMENT '卷烟销量同期年累计(万支)',
	md03_cgt_10th_com_sale_amt_y_al DECIMAL(54, 18) COMMENT '卷烟销售金额同期年累计(万元)',
	create_time DATETIME COMMENT '创建时间'
)
PARTITIONED BY (
	ds STRING
)
STORED AS ALIORC
TBLPROPERTIES (
	'comment' = '商业_卷烟购销存年表'
)
LIFECYCLE 7;